# Generated by Django 4.2 on 2023-04-11 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_name', models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Cable Name')),
                ('cap_number', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Cap Number')),
                ('clutch_number', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Clutch Number')),
                ('inductor_type', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Inductor Type')),
                ('machine', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Machine')),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
