# Generated by Django 4.2 on 2023-04-25 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('cable', models.CharField(max_length=50)),
                ('cable_quantity', models.PositiveIntegerField()),
                ('company_name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cable',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='cable',
            name='cable_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Cable Name'),
        ),
    ]
