# Generated by Django 4.2 on 2023-04-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0002_alter_cable_options_alter_cable_cable_name_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cable',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
