# Generated by Django 4.2 on 2023-05-03 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0003_order_confirm_user_order_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='machine',
            field=models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Machine'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
