# Generated by Django 4.2 on 2023-06-05 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0005_alter_cable_inductor_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='cable',
            name='inductor_type',
            field=models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Inductor Type'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='machine',
            field=models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Machine'),
        ),
    ]
